import { IoIosBed } from "react-icons/io";
import Room1 from "../images/Room1.jpg";
import Room2 from "../images/Room2.jpg";
import Room3 from "../images/Room3.jpg";
import Pool1 from "../images/pool.jpg";

const Data = [
  {
    id: '1',
    category: "bedroom",
    img: Room1,
    discount: "20% OFF",
    title: "Deluxe Contrast Room",
    icon1: <IoIosBed />,
    icon2: <IoIosBed />,
    icon3: <IoIosBed />,
    bed: 2,
    bathroom: 1,
    rating: 144,
    price: 85,
  },
  {
    id: 2,
    category: "guest room",
    img: Room1,
    discount: "20% OFF",
    title: "Deluxe Contrast Room",
    icon1: <IoIosBed />,
    icon2: <IoIosBed />,
    icon3: <IoIosBed />,
    bed: 2,
    bathroom: 1,
    rating: 144,
    price: 85,
  },
  {
    id: 3,
    img: Room1,
    category: "meeting room",
    discount: "20% OFF",
    title: "Deluxe Contrast Room",
    icon1: <IoIosBed />,
    icon2: <IoIosBed />,
    icon3: <IoIosBed />,
    bed: 2,
    bathroom: 1,
    rating: 144,
    price: 85,
  },
  {
    id: 4,
    img: Room2,
    category: "gym center",
    discount: "20% OFF",
    title: "Deluxe Contrast Room",
    icon1: <IoIosBed />,
    icon2: <IoIosBed />,
    icon3: <IoIosBed />,
    bed: 2,
    bathroom: 1,
    rating: 144,
    price: 85,
  },
  {
    id: 5,
    img: Room1,
    category: "swimming pool",
    discount: "20% OFF",
    title: "Deluxe Contrast Room",
    icon1: <IoIosBed />,
    icon2: <IoIosBed />,
    icon3: <IoIosBed />,
    bed: 2,
    bathroom: 1,
    rating: 144,
    price: 85,
  },
  {
    id: 6,
    category: "bedroom",
    img: Room1,
    discount: "20% OFF",
    title: "Deluxe Contrast Room",
    icon1: <IoIosBed />,
    icon2: <IoIosBed />,
    icon3: <IoIosBed />,
    bed: 2,
    bathroom: 1,
    rating: 144,
    price: 85,
  },
  {
    id: 7,
    category: "guest room",
    img: Room1,
    discount: "20% OFF",
    title: "Deluxe Contrast Room",
    icon1: <IoIosBed />,
    icon2: <IoIosBed />,
    icon3: <IoIosBed />,
    bed: 2,
    bathroom: 1,
    rating: 144,
    price: 85,
  },
  {
    id: 8,
    img: Room1,
    category: "meeting room",
    discount: "20% OFF",
    title: "Deluxe Contrast Room",
    icon1: <IoIosBed />,
    icon2: <IoIosBed />,
    icon3: <IoIosBed />,
    bed: 2,
    bathroom: 1,
    rating: 144,
    price: 85,
  },
  {
    id: 9,
    category: "gym center",
    img: Room1,
    discount: "20% OFF",
    title: "Deluxe Contrast Room",
    icon1: <IoIosBed />,
    icon2: <IoIosBed />,
    icon3: <IoIosBed />,
    bed: 2,
    bathroom: 1,
    rating: 144,
    price: 85,
  },
  {
    id: 10,
    category: "swimming pool",
    img: Room3,
    discount: "20% OFF",
    title: "Deluxe Contrast Room",
    icon1: <IoIosBed />,
    icon2: <IoIosBed />,
    icon3: <IoIosBed />,
    bed: 2,
    bathroom: 1,
    rating: 144,
    price: 85,
  },
  {
    id: 11,
    category: "bedroom",
    img: Room1,
    discount: "20% OFF",
    title: "Deluxe Contrast Room",
    icon1: <IoIosBed />,
    icon2: <IoIosBed />,
    icon3: <IoIosBed />,
    bed: 2,
    bathroom: 1,
    rating: 144,
    price: 85,
  },
  {
    id: 12,
    img: Room1,
    category: "guest room",
    discount: "20% OFF",
    title: "Deluxe Contrast Room",
    icon1: <IoIosBed />,
    icon2: <IoIosBed />,
    icon3: <IoIosBed />,
    bed: 2,
    bathroom: 1,
    rating: 144,
    price: 85,
  },
  {
    id: 13,
    category: "meeting room",
    img: Room1,
    discount: "20% OFF",
    title: "Deluxe Contrast Room",
    icon1: <IoIosBed />,
    icon2: <IoIosBed />,
    icon3: <IoIosBed />,
    bed: 2,
    bathroom: 1,
    rating: 144,
    price: 85,
  },
  {
    id: 14,
    category: "gym center",
    img: Room1,
    discount: "20% OFF",
    title: "Deluxe Contrast Room",
    icon1: <IoIosBed />,
    icon2: <IoIosBed />,
    icon3: <IoIosBed />,
    bed: 2,
    bathroom: 1,
    rating: 144,
    price: 85,
  },
  {
    id: 15,
    category: "swimming pool",
    img: Pool1,
    discount: "20% OFF",
    title: "Swimming pool",
    icon1: <IoIosBed />,
    icon2: <IoIosBed />,
    icon3: <IoIosBed />,
    bed: 2,
    bathroom: 1,
    rating: 144,
    price: 85,
  },
  {
    id: 16,
    img: Room1,
    discount: "20% OFF",
    title: "Deluxe Contrast Room",
    icon1: <IoIosBed />,
    icon2: <IoIosBed />,
    icon3: <IoIosBed />,
    bed: 2,
    bathroom: 1,
    rating: 144,
    price: 85,
  },
  {
    id: 17,
    img: Room1,
    discount: "20% OFF",
    title: "Deluxe Contrast Room",
    icon1: <IoIosBed />,
    icon2: <IoIosBed />,
    icon3: <IoIosBed />,
    bed: 2,
    bathroom: 1,
    rating: 144,
    price: 85,
  },
  {
    id: 18,
    img: Room1,
    discount: "20% OFF",
    title: "swimming pool",
    icon1: <IoIosBed />,
    icon2: <IoIosBed />,
    icon3: <IoIosBed />,
    bed: 2,
    bathroom: 1,
    rating: 144,
    price: 85,
  },
];

export default Data;
